### ISSUE TITLE
Problem with PDF export

### ISSUE THREAD

**Issue by Trefex** [will-moore/figure#22] opened 2014-10-08 15:42 UTC
Dear Will,

In the export, there is a problem depending on which PDF reader you use.

For instance, when using SumatraPDF (very popular) the text layers are there but in black, whereas in Adobe, they are in the correct colors.

What could be the issue here?

![problem](https://cloud.githubusercontent.com/assets/2877665/4562062/bbd685a2-4f01-11e4-9003-5df7a2a61049.PNG)

**Comment by Trefex** [comment] 2015-02-18 23:37
@will-moore This was reported again by a user. Did you figure out what is going on ?

**Comment by will-moore** [comment] 2015-02-19 00:01
@Trefex I'm afraid I haven't got any further with this.
I'm kinda assuming it's a reportlab bug/issue but I don't see anything when googling or looking here: https://bitbucket.org/rptlab/reportlab/issues

I try to see if I can reproduce it on my machine, then see if there's any workaround (E.g. setting colours in a different way etc), but I'm not too optimistic I'm afraid.
I might open a new issue at the link above if I can't get anywhere myself.

**Comment by will-moore** [comment] 2015-02-22 00:09
@Trefex - Good news! I worked out that this was my bug with the way I was setting colors in reportlab. Fixed in https://github.com/will-moore/figure/pull/58

As you can see, it was a pretty simple fix, so if you want to make those same changes to your local PDF script then this should work. NB: Don't just download the latest version of the script from the PR, since it now contains other changes that will break with OMERO.figure 1.0.0. But applying the diff will be OK.

**Closed by will-moore** 2015-02-22 00:09 UTC

**Comment by Trefex** [comment] 2015-02-27 11:24
@will-moore great news! I will let you know the outcome. Best,

**Comment by Trefex** [comment] 2015-03-06 15:15
@will-moore the problem is fixed. Thanks !
